/*
 * Vista_Inicio.java
 */

package view;

import Main.CommonVar;
import Main.Controller;
import com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 * Initial view dialog
 * @author Ismael Duque García
 * @version 1.0
 */
public class InitialView extends JFrame {

    /**
     * Controlador asociado a esta vista.
     */
    private Controller _controller;

    /**
     * Initial view constructor.
     * @param controller Main controller.
     */
    public InitialView(Controller controller) {

        try{//selecciona el LookAndFeel del sistema actual
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch (Exception e){
            e.getMessage();
        }

        initComponents();

        _controller = controller;

        //When the cursor is on the Nickname textfield and the user presses Enter
        _jtfNickname.addActionListener(new ActionListener(){
            @Override
                public void actionPerformed(ActionEvent e){
                    if(!_jtfFirstName.getText().isEmpty() && !_jtfLastName.getText().isEmpty() &&
                            !_jtfNickname.getText().isEmpty())
                        _jbOKActionPerformed(e);
                }});

        /*centra la venta en la pantalla*/
        this.pack();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }


    public void mostrarVentanaPrincipal() {
        this.setVisible(true);
    }
    /** This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _jdUserName = new javax.swing.JDialog();
        _jtfFirstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        _jbOK = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        _jtfLastName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        _jtfNickname = new javax.swing.JTextField();
        _jbDataAdmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        _jbUserPanel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        _jdUserName.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        _jdUserName.setTitle("Information Required");
        _jdUserName.setMinimumSize(new java.awt.Dimension(300, 200));
        _jdUserName.setModal(true);
        _jdUserName.setResizable(false);

        _jtfFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                _jtfFirstNameKeyTyped(evt);
            }
        });

        jLabel2.setText("First Name:");

        jLabel3.setText("Please, introduce the following information:");

        _jbOK.setText("OK");
        _jbOK.setEnabled(false);
        _jbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _jbOKActionPerformed(evt);
            }
        });

        jLabel4.setText("Last Name:");

        _jtfLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                _jtfLastNameKeyTyped(evt);
            }
        });

        jLabel6.setText("Nickname:");

        _jtfNickname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                _jtfNicknameKeyTyped(evt);
            }
        });

        _jdUserName.setLocationRelativeTo(null);

        org.jdesktop.layout.GroupLayout _jdUserNameLayout = new org.jdesktop.layout.GroupLayout(_jdUserName.getContentPane());
        _jdUserName.getContentPane().setLayout(_jdUserNameLayout);
        _jdUserNameLayout.setHorizontalGroup(
            _jdUserNameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(_jdUserNameLayout.createSequentialGroup()
                .add(_jdUserNameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(_jdUserNameLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel3))
                    .add(_jdUserNameLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(_jtfNickname, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                    .add(_jdUserNameLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(_jtfLastName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                    .add(_jdUserNameLayout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(_jdUserNameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(_jbOK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(_jdUserNameLayout.createSequentialGroup()
                                .add(jLabel2)
                                .add(5, 5, 5)
                                .add(_jtfFirstName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))))
                .add(22, 22, 22))
        );
        _jdUserNameLayout.setVerticalGroup(
            _jdUserNameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(_jdUserNameLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .add(25, 25, 25)
                .add(_jdUserNameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(_jtfFirstName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(8, 8, 8)
                .add(_jdUserNameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(_jtfLastName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(_jdUserNameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(_jtfNickname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12)
                .add(_jbOK)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Questionnaire Aplication");
        setResizable(false);

        _jbDataAdmin.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 11));
        _jbDataAdmin.setText("DATA ADMINISTRATION");
        _jbDataAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _jbDataAdminActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14));
        jLabel1.setText("ROBOT HOUSE STUDIES QUESTIONNAIRE");

        _jbUserPanel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 11));
        _jbUserPanel.setText("USER QUESTIONNAIRE");
        _jbUserPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _jbUserPanelActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/University of Hertfordshire.gif"))); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(33, 33, 33)
                .add(_jbDataAdmin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(60, 60, 60)
                .add(_jbUserPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(48, 48, 48))
            .add(layout.createSequentialGroup()
                .add(93, 93, 93)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel5, 0, 0, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(30, 30, 30)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(_jbDataAdmin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(_jbUserPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _jbDataAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__jbDataAdminActionPerformed
        _controller.setScreen("Admin", "", "", "");
        this.setVisible(false);
}//GEN-LAST:event__jbDataAdminActionPerformed
  
    private void _jbUserPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__jbUserPanelActionPerformed
        this._jdUserName.setVisible(true);
        this._jdUserName.setLocationRelativeTo(null);
}//GEN-LAST:event__jbUserPanelActionPerformed

    private void _jbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__jbOKActionPerformed
        _controller.setScreen(CommonVar.USER, _jtfFirstName.getText(), _jtfLastName.getText(), _jtfNickname.getText());
        this._jdUserName.dispose();
        this.setVisible(false);
    }//GEN-LAST:event__jbOKActionPerformed

    private void _jtfFirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__jtfFirstNameKeyTyped
        if(!this._jtfFirstName.getText().isEmpty() && !this._jtfLastName.getText().isEmpty() &&
                !this._jtfNickname.getText().isEmpty())
            this._jbOK.setEnabled(true);
        else this._jbOK.setEnabled(false);
    }//GEN-LAST:event__jtfFirstNameKeyTyped

private void _jtfLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__jtfLastNameKeyTyped
        if(!this._jtfFirstName.getText().isEmpty() && !this._jtfLastName.getText().isEmpty() &&
                !this._jtfNickname.getText().isEmpty())
            this._jbOK.setEnabled(true);
        else this._jbOK.setEnabled(false);
}//GEN-LAST:event__jtfLastNameKeyTyped

private void _jtfNicknameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__jtfNicknameKeyTyped
        if(!this._jtfFirstName.getText().isEmpty() && !this._jtfLastName.getText().isEmpty() &&
                !this._jtfNickname.getText().isEmpty())
            this._jbOK.setEnabled(true);
        else this._jbOK.setEnabled(false);
}//GEN-LAST:event__jtfNicknameKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _jbDataAdmin;
    private javax.swing.JButton _jbOK;
    private javax.swing.JButton _jbUserPanel;
    private javax.swing.JDialog _jdUserName;
    private javax.swing.JTextField _jtfFirstName;
    private javax.swing.JTextField _jtfLastName;
    private javax.swing.JTextField _jtfNickname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
